### PR TITLE
docs(contribution): Clone contribution agreement from soda

### PR DESCRIPTION
**Pull request by champillon**
docs(contribution): Clone contribution agreement from soda
to make the same agreement for all ETDA projects

### CODE REVIEW

**Comment by varokas** [comment]
I'm not sure why git-setup.sh is checked in?

**Comment by champillon** [comment]
@varokas  Oppss I'm forgot that only ETDA can put the schema haha!!!

**Comment by varokas** [comment]
That's not what I meant. I think we should have a blog somewhere that outline how to contribute rather than a script. idk.

**Comment by varokas** [comment]
LGTM this

**Comment by varokas** [comment]
the removed code. for reference: 

```
#!/usr/bin/env bash
 
 # add main repo as an upstream remote so that we can pull lastest from main repo
 echo "* Add main repository as upstream remote"
 git remote add upstream git@github.com:ETDA/etax-schema.git
 
 # add commit template to git config
 echo "* Add git commit guideline into commit template"
 git config --local commit.template .gitmessage
```

**Comment by champillon** [comment]
Ummm.... I see. better la, we can use the wiki somehow I think we do need the separated web blog on this as another Thai OpenSource Contribution Knowledge Service.

**Comment by mahasak** [comment]
LGTM :D

**Pull request merged**
