### PR TITLE
Fix duplicate ThaiDocumentNameCodeInvoiceContentType and MessageFunctionCodeContentType

### PR DESCRIPTION
**Pull request by varokas**
From the two remaining error messages in #4. 

## ThaiDocumentNameCodeInvoiceContentType
```
[ERROR] 'ThaiDocumentNameCodeInvoice' is already defined
  line 51 of file:/Users/varokas/Documents/projects/etax-schema/schema/XMLSchemaV2/uncefact/codelist/standard/ThaiDocumentNameCode_Invoice_1p0.xsd

[ERROR] (related to above error) the first definition appears here
  line 51 of file:/Users/varokas/Documents/projects/etax-schema/schema/XMLSchemaV2/ETDA/codelist/standard/ThaiDocumentNameCode_Invoice_1p0.xsd

[ERROR] 'ThaiDocumentNameCodeInvoiceContentType' is already defined
  line 122 of file:/Users/varokas/Documents/projects/etax-schema/schema/XMLSchemaV2/uncefact/codelist/standard/ThaiDocumentNameCode_Invoice_1p0.xsd

[ERROR] (related to above error) the first definition appears here
  line 57 of file:/Users/varokas/Documents/projects/etax-schema/schema/XMLSchemaV2/ETDA/codelist/standard/ThaiDocumentNameCode_Invoice_1p0.xsd
```

This is because we have 2 duplicate documents `ETDA/codelist/standard/ThaiDocumentNameCode_Invoice_1p0.xsd` and `uncefact/codelist/standard/ThaiDocumentNameCode_Invoice_1p0.xsd`

They both have the same content (diff result is empty).

So I decided to delete uncefact one because at least one place is referencing the ETDA version which is `QualifiedDataType_1p0.xsd` line 144

```
  <xsd:import namespace="urn:etda:uncefact:codelist:standard:ThaiDocumentNameCode_Invoice:1"
    schemaLocation="../../codelist/standard/ThaiDocumentNameCode_Invoice_1p0.xsd"/>
```

## MessageFunctionCodeContentType
```
[ERROR] 'MessageFunctionCode' is already defined
  line 28 of file:/home/travis/build/ETDA/etax-schema/schema/XMLSchemaV2/uncefact/codelist/standard/UNECE_MessageFunctionCode_D14A.xsd
[ERROR] (related to above error) the first definition appears here
  line 28 of file:/home/travis/build/ETDA/etax-schema/schema/XMLSchemaV2/ETDA/codelist/standard/ThaiMessageFunctionCode_1p0.xsd
[ERROR] 'MessageFunctionCodeContentType' is already defined
  line 558 of file:/home/travis/build/ETDA/etax-schema/schema/XMLSchemaV2/uncefact/codelist/standard/UNECE_MessageFunctionCode_D14A.xsd
[ERROR] (related to above error) the first definition appears here
  line 34 of file:/home/travis/build/ETDA/etax-schema/schema/XMLSchemaV2/ETDA/codelist/standard/ThaiMessageFunctionCode_1p0.xsd
```

Again the two duplicate documents `UNECE_MessageFunctionCode_D14A.xsd` and `ThaiMessageFunctionCode_1p0.xsd` has the exact same diff. 

I retained the UNECE one because it is referenced in QualifiedDataType.xsd
```
  <xsd:import namespace="urn:un:unece:uncefact:codelist:standard:UNECE:MessageFunctionCode:D14A"
    schemaLocation="../../../uncefact/codelist/standard/UNECE_MessageFunctionCode_D14A.xsd"/>
```

### CODE REVIEW

**Comment by pragasitcha** [comment]
Dear @varokas  @NopponP  

our XML team reviewed and approved this PR krub 

They will check why ThaiDocumentNameCode_Invoice_1p0.xsd exist in  
uncefact/codelist/standard/  path and  ThaiMessageFunctionCode_1p0.xsd is not valid . we ll update schema file on RD website

**Comment by varokas** [comment]
If you approve. Just comment "LGTM" and merge. Thanks for quick response :)

**Comment by varokas** [comment]
Also if you have any change. Could you open a pull request to this repo ?
So we are synchronize on the change. If you need technical details you can
chat with me on that

**Comment by pragasitcha** [comment]
OK krub : )

**Pull request merged**
